"use client"

import { useState } from "react"
import HeroSection from "../hero-section"
import StoriesDashboard, { StoriesForm } from "../components/stories-dashboard"
import { Activity, ArrowUpRight, Bike, Dumbbell, Gamepad2, Goal, HeartHandshake, MoveUpRight, Send, Target, Trophy, Users, Waves } from "lucide-react"

const sports = [
  { name: "Badminton", detail: "Gerak cepat, rally seru, dan sportivitas.", icon: Activity, number: "01" },
  { name: "Running", detail: "Satu langkah kecil, banyak cerita besar.", icon: MoveUpRight, number: "02" },
  { name: "Panahan", detail: "Fokus pada target, tenang dalam proses.", icon: Target, number: "03" },
  { name: "Futsal", detail: "Kerja sama tim sampai peluit akhir.", icon: Goal, number: "04" },
  { name: "Tenis Lapangan", detail: "Strategi, stamina, dan permainan berkelas.", icon: Trophy, number: "05" },
  { name: "Tenis Meja", detail: "Refleks cepat, kompetisi bersahabat.", icon: Waves, number: "06" },
  { name: "e-Sport", detail: "Taktik digital, kolaborasi, dan fair play.", icon: Gamepad2, number: "07" },
]

export default function Page() {
  const [showForm, setShowForm] = useState(false)
  return <main className="min-h-screen overflow-hidden bg-[#f7f8fa] text-[#12243a]">
    <HeroSection />

    <section id="mission" className="relative px-5 py-24 md:px-10 md:py-32">
      <div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[0.8fr_1.2fr] md:items-end">
        <div><p className="mb-5 text-xs font-bold uppercase tracking-[.28em] text-[#c18b38]">Our purpose · Tujuan bersama</p>
          <h2 className="text-4xl font-black leading-[1.05] tracking-tight md:text-6xl">LEBIH AKTIF.<br/><span className="text-[#164a7b]">LEBIH KOMPAK.</span></h2>
        </div>
        <div className="border-l-2 border-[#d7a34c] pl-6 md:pl-9"><p className="text-xl leading-relaxed text-slate-700 md:text-2xl">Madu Jakbar Sport hadir sebagai rumah bagi semangat olahraga pegawai Madya Dua Jakarta Barat—ruang untuk bergerak, bertumbuh, menjaga kebugaran, dan mempererat kebersamaan lintas tim.</p><p className="mt-5 max-w-2xl text-base leading-7 text-slate-500">Bukan soal siapa yang paling cepat atau paling jago. Ini tentang konsistensi, sportivitas, saling mendukung, dan menciptakan cerita baik di setiap kegiatan.</p></div>
      </div>
      <div className="mx-auto mt-16 grid max-w-7xl grid-cols-2 gap-3 md:grid-cols-4"><div className="rounded-2xl bg-[#102b46] p-6 text-white"><Users className="mb-8"/><p className="text-2xl font-black">Satu unit</p><p className="mt-1 text-sm text-white/65">Banyak energi positif</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><HeartHandshake className="mb-8 text-[#b78332]"/><p className="text-2xl font-black">Saling dukung</p><p className="mt-1 text-sm text-slate-500">Kompak di dalam dan luar lapangan</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><Trophy className="mb-8 text-[#b78332]"/><p className="text-2xl font-black">Sportif</p><p className="mt-1 text-sm text-slate-500">Menang dengan rendah hati</p></div><div className="rounded-2xl bg-[#e7edf3] p-6"><Activity className="mb-8 text-[#164a7b]"/><p className="text-2xl font-black">Konsisten</p><p className="mt-1 text-sm text-slate-600">Sehat jadi kebiasaan</p></div></div>
    </section>

    <section id="community" className="bg-[#102b46] px-5 py-24 text-white md:px-10 md:py-28">
      <div className="mx-auto max-w-7xl"><div className="mb-14 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.28em] text-[#e0b56d]">Find your game · Temukan cabangmu</p><h2 className="text-4xl font-black tracking-tight md:text-6xl">ONE COMMUNITY.<br/><span className="text-[#e0b56d]">MANY WAYS TO PLAY.</span></h2></div><p className="max-w-md text-base leading-7 text-white/65">Dari lapangan sampai arena digital, setiap minat punya tempat. Kenali cabang olahraga yang menjadi bagian dari keluarga Madu Jakbar Sport.</p></div>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{sports.map((sport) => { const Icon = sport.icon; return <article key={sport.name} className="group rounded-2xl border border-white/10 bg-white/[.045] p-6 transition duration-300 hover:-translate-y-1 hover:border-[#e0b56d]/70 hover:bg-white/[.08]"><div className="mb-10 flex items-start justify-between"><span className="text-xs font-bold tracking-[.2em] text-[#e0b56d]">{sport.number}</span><Icon className="text-white/70 transition group-hover:text-[#e0b56d]" size={25}/></div><h3 className="text-2xl font-bold">{sport.name}</h3><p className="mt-2 text-sm leading-6 text-white/60">{sport.detail}</p></article> })}<article className="flex flex-col justify-between rounded-2xl bg-[#e0b56d] p-6 text-[#102b46]"><div><p className="text-xs font-black uppercase tracking-[.2em]">Punya ide kegiatan?</p><h3 className="mt-4 text-2xl font-black">Bikin gerakan berikutnya bareng-bareng.</h3></div><button onClick={() => document.querySelector("#join")?.scrollIntoView({behavior:"smooth"})} className="mt-8 flex items-center gap-2 self-start text-sm font-bold">Ikut berkontribusi <ArrowUpRight size={18}/></button></article></div>
      </div>
    </section>

    <section id="testimonials" className="px-5 py-24 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="mb-14 max-w-3xl"><p className="mb-4 text-xs font-bold uppercase tracking-[.28em] text-[#b78332]">Voices of Madu · Suara kebersamaan</p><h2 className="text-4xl font-black tracking-tight md:text-6xl">CERITA DI BALIK<br/><span className="text-[#164a7b]">SETIAP KEGIATAN.</span></h2><p className="mt-6 text-lg leading-8 text-slate-600">Pesan pimpinan menjadi pengingat arah dan semangat bersama. Cerita anggota menjadi jejak kecil yang merangkai perjalanan komunitas kita.</p></div>
        <div className="mb-12 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="rounded-3xl bg-[#e8edf2] p-8 md:p-10"><div className="mb-8 flex h-12 w-12 items-center justify-center rounded-full bg-[#102b46] text-[#e0b56d]"><Trophy/></div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#164a7b]">Pesan Kepala Unit Kerja</p><blockquote className="mt-5 text-2xl font-semibold leading-relaxed text-[#102b46]">“Semoga Madu Jakbar Sport menjadi ruang untuk menjaga kesehatan, memperkuat kebersamaan, dan menumbuhkan sportivitas. Terus bergerak, saling mendukung, dan bawa energi positif dalam setiap kegiatan.”</blockquote><p className="mt-7 text-sm font-bold text-slate-600">Kepala KPP Madya Dua Jakarta Barat</p><p className="mt-1 text-xs text-slate-500">Draf pesan — silakan konfirmasi redaksi resmi sebelum dipublikasikan.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-7 md:p-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b78332]">Community journal</p><h3 className="mt-2 text-2xl font-black">Kesan & pesan anggota</h3><p className="mt-2 max-w-lg text-sm leading-6 text-slate-500">Cerita singkat dari kegiatan yang sudah diikuti. Kiriman terbaru akan tampil di sini setelah sistem penyimpanan online dikonfigurasi.</p></div><button onClick={() => setShowForm(v => !v)} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-[#164a7b] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#102b46]"><Send size={16}/> {showForm ? "Tutup form" : "Tulis cerita"}</button></div>{showForm && <div className="mt-7"><StoriesForm /></div>}</div></div>
        <StoriesDashboard />
      </div></section>

    <section id="join" className="relative overflow-hidden bg-[#0a1d30] px-5 py-24 text-white md:px-10 md:py-32"><div className="pointer-events-none absolute -right-20 -top-28 h-96 w-96 rounded-full border border-white/10"/><div className="pointer-events-none absolute -right-2 -top-10 h-60 w-60 rounded-full border border-[#e0b56d]/30"/><div className="relative mx-auto grid max-w-7xl gap-10 md:grid-cols-[1fr_auto] md:items-end"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.3em] text-[#e0b56d]">Your move · Langkahmu dimulai di sini</p><h2 className="max-w-4xl text-5xl font-black leading-[.98] tracking-tight md:text-7xl">MOVE TOGETHER.<br/><span className="text-[#e0b56d]">GROW STRONGER.</span></h2><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">Jadi bagian dari cerita Madu Jakbar Sport. Ikuti kegiatan, dukung rekan, dan bagikan momen yang layak dikenang.</p></div><button onClick={() => { setShowForm(true); document.querySelector("#testimonials")?.scrollIntoView({behavior:"smooth"}) }} className="inline-flex items-center justify-center gap-3 rounded-full bg-[#e0b56d] px-7 py-4 font-black text-[#102b46] transition hover:bg-white">BAGIKAN CERITAMU <ArrowUpRight size={20}/></button></div><div className="relative mx-auto mt-20 flex max-w-7xl flex-col justify-between gap-4 border-t border-white/15 pt-6 text-xs tracking-wide text-white/45 md:flex-row"><span>MADU JAKBAR SPORT · KPP MADYA DUA JAKARTA BARAT</span><a href="#hero" className="hover:text-white">Kembali ke atas ↑</a><span>Sehat bersama. Kompak selamanya.</span></div></section>
  </main>
}
